name: Supabase Send Daily Report

on:
  schedule:
    - cron: '35 1 * * *' # todos los días a la 01:35 UTC
  workflow_dispatch:

jobs:
  call-supabase-send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function (send_daily_report)
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          curl -X POST https://ukygfdjxhmlqhxohnvzi.supabase.co/functions/v1/send_daily_report \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY"
